import avatarApi from './avatars';
const emailData = [
  {
    id: '1',
    avatar: avatarApi[6],
    name: 'John Doe',
    date: 'May, 11 2018',
    subject: 'Lorem ipsum dolor sit amet',
    category: '',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed urna in justo euismod condimentum. Fusce placerat enim et odio molestie sagittis. Vestibulum dignissim orci vitae eros rutrum euismod.',
    attachment: [],
    stared: false,
  },
  {
    id: '2',
    avatar: avatarApi[8],
    name: 'Jim Doe',
    date: 'May, 12 2018',
    subject: 'Nunc quis sem quis velit tincidunt',
    category: 'social',
    content: 'Maecenas nisl libero, tincidunt id odio id, feugiat vulputate quam. Vestibulum feugiat rhoncus metus. In non erat et ipsum molestie porta sit amet ut felis. Vestibulum a massa vestibulum, gravida odio id, fringilla ipsum. Ut sed eros finibus, placerat orci id, dapibus mauris.',
    attachment: [],
    stared: true,
  },
  {
    id: '3',
    avatar: avatarApi[2],
    name: 'Jane Doe',
    date: 'May, 13 2018',
    subject: 'Vivamus sit',
    category: 'updates',
    content: 'Pellentesque ullamcorper aliquet ultrices.',
    attachment: [],
    stared: true,
  },
  {
    id: '4',
    avatar: avatarApi[9],
    name: 'Jinx Doe',
    date: 'May, 13 2018',
    subject: 'Vestibulum faucibus eget erat eget pretium',
    category: 'social',
    content: 'Nulla vehicula leo ut augue tincidunt, placerat tempus nulla rutrum. Integer orci justo, fringilla at faucibus vel, pulvinar in eros. Suspendisse eleifend nunc non varius rhoncus. Nam posuere accumsan porta. Integer id orci sed ante tincidunt tincidunt sit amet sed libero.',
    attachment: [],
    stared: false,
  },
  {
    id: '5',
    avatar: avatarApi[4],
    name: 'Jihan Doe',
    date: 'May, 15 2018',
    subject: 'Aliquam venenatis magna et odio lobortis maximus',
    category: 'promos',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed urna in justo euismod condimentum. Fusce placerat enim et odio molestie sagittis. Vestibulum dignissim orci vitae eros rutrum euismod.',
    attachment: [],
    stared: false,
  },
  {
    id: '6',
    avatar: avatarApi[7],
    name: 'Johny Doe',
    date: 'May, 15 2018',
    subject: 'Vivamus sit amet interdum elit',
    category: 'forums',
    content: 'Integer orci justo, fringilla at faucibus vel, pulvinar in eros.',
    attachment: [],
    stared: false,
  },
  {
    id: '7',
    avatar: avatarApi[5],
    name: 'Jane Doe',
    date: 'May, 16 2018',
    subject: 'Lorem ipsum dolor sit amet',
    category: 'spam',
    content: 'Nam posuere accumsan porta.',
    attachment: [],
    stared: true,
  },
  {
    id: '8',
    avatar: avatarApi[6],
    name: 'Me',
    date: 'May, 16 2018',
    subject: 'Lorem ipsum dolor sit amet',
    category: 'sent',
    content: 'Nam posuere accumsan porta.',
    attachment: [],
    stared: false,
  },
  {
    id: '9',
    avatar: avatarApi[7],
    name: 'James Doe',
    date: 'May, 17 2018',
    subject: 'Pellentesque ullamcorper aliquet ultrices',
    category: 'sent',
    content: 'Cras convallis lacus orci, tristique tincidunt magna consequat in. In vel pulvinar est, at euismod libero. Quisque ut metus sit amet augue rutrum feugiat. Vestibulum bibendum nisi eget magna malesuada, at mattis eros efficitur. Vivamus facilisis quam ullamcorper iaculis gravida.',
    attachment: [],
    stared: true,
  },
  {
    id: '10',
    avatar: avatarApi[3],
    name: 'Jihan Doe',
    date: 'May, 17 2018',
    subject: 'Dolor',
    category: 'sent',
    content: 'Nulla vehicula leo ut augue tincidunt, placerat tempus nulla rutrum. Integer orci justo, fringilla at faucibus vel, pulvinar in eros.',
    attachment: [],
    stared: false,
  },
  {
    id: '11',
    avatar: avatarApi[10],
    name: 'Johny Doe',
    date: 'May, 20 2018',
    subject: 'Vivamus sit amet interdum elit',
    category: 'spam',
    content: 'Integer orci justo, fringilla at faucibus vel, pulvinar in eros.',
    attachment: [],
    stared: false,
  },
];

export default emailData;
