import imgApi from './images';
const productData = [
  {
    id: '1',
    name: 'Cras convallis lacus orc',
    thumbnail: imgApi[21],
    desc: 'Curabitur egestas consequat lorem, vel fermentum augue porta id.',
    ratting: 4,
    price: 30,
    prevPrice: 0,
    discount: '',
    soldout: false,
  },
  {
    id: '2',
    name: 'Vivamus sit amet interdum elit',
    thumbnail: imgApi[22],
    desc: 'Maecenas nisl libero, tincidunt id odio id, feugiat vulputate quam.',
    ratting: 0,
    price: 15,
    prevPrice: 150,
    discount: '90%',
    soldout: false,
  },
  {
    id: '3',
    name: 'Fusce placerat enim et odio molestie sagittis',
    thumbnail: imgApi[23],
    desc: 'Duis tristique metus magna, lobortis aliquam risus euismod sit amet',
    ratting: 5,
    price: 30,
    prevPrice: 0,
    discount: '',
    soldout: true,
  },
  {
    id: '4',
    name: 'Pellentesque ac bibendum tortor',
    thumbnail: imgApi[24],
    desc: 'Nam posuere accumsan porta',
    ratting: 2,
    price: 80,
    prevPrice: 100,
    discount: '20%',
    soldout: false,
  },
  {
    id: '5',
    name: 'Curabitur egestas consequat lorem',
    thumbnail: imgApi[25],
    desc: 'Aenean sit amet magna vel magna fringilla fermentum',
    ratting: 5,
    price: 50,
    prevPrice: 0,
    discount: '',
    soldout: false,
  },
  {
    id: '6',
    name: 'Aenean facilisis vitae purus facilisis semper',
    thumbnail: imgApi[26],
    desc: 'Vestibulum bibendum nisi eget magna malesuada',
    ratting: 4,
    price: 75,
    prevPrice: 100,
    discount: '25%',
    soldout: false,
  },
  {
    id: '7',
    name: 'Aenean sit amet magna vel magna fringilla fermentum',
    thumbnail: imgApi[27],
    desc: 'Nam posuere accumsan porta. Integer id orci sed ante tincidunt tincidunt sit amet sed libero.',
    ratting: 5,
    price: 20,
    prevPrice: 16,
    discount: '20%',
    soldout: false,
  },
  {
    id: '8',
    name: 'Ut sed eros finibus',
    thumbnail: imgApi[28],
    desc: 'Curabitur egestas consequat lorem, vel fermentum augue porta id.',
    ratting: 1,
    price: 30,
    prevPrice: 0,
    discount: '',
    soldout: false,
  },
  {
    id: '9',
    name: 'Nulla lobortis nunc vitae nisi',
    thumbnail: imgApi[29],
    desc: 'Sed mi neque, convallis at ipsum at, blandit pretium enim',
    ratting: 4,
    price: 50,
    prevPrice: 100,
    discount: '50%',
    soldout: false,
  },
  {
    id: '10',
    name: 'Nam posuere accumsan',
    thumbnail: imgApi[30],
    desc: 'Integer id orci sed ante tincidunt tincidunt sit amet sed libero.',
    ratting: 5,
    price: 30,
    prevPrice: 0,
    discount: '',
    soldout: true,
  },
  {
    id: '11',
    name: 'Cras convallis lacus orc',
    thumbnail: imgApi[37],
    desc: 'Curabitur egestas consequat lorem, vel fermentum augue porta id.',
    ratting: 4,
    price: 66,
    prevPrice: 200,
    discount: '67%',
    soldout: false,
  },
];

export default productData;
