const screenshoots = {
  dashboardv2: '/images/ss/dashboardv2.jpg',
  trackingTable: '/images/ss/tracking_table.jpg',
  crudTable: '/images/ss/crud_table.jpg',
  treetable: '/images/ss/treetable.jpg',
  datatable: '/images/ss/datatable.jpg',
  ratting: '/images/ss/ratting.jpg',
  slider: '/images/ss/slider.jpg',
  texteditor: '/images/ss/texteditor.jpg',
  upload: '/images/ss/upload.jpg',
  imageLightbox: '/images/ss/imageLightbox.jpg',
  dividers: '/images/ss/dividers.jpg',
  pagination: '/images/ss/pagination.jpg',
  sliderCarousel: '/images/ss/sliderCarousel.jpg',
  sliderCarousel2: '/images/ss/sliderCarousel2.jpg',
  chat: '/images/ss/chat.jpg',
  email: '/images/ss/email.jpg',
  ecommerce: '/images/ss/ecommerce.jpg',
  socmed: '/images/ss/socmed.jpg',
  profile: '/images/ss/profile.jpg',
  gallery: '/images/ss/gallery.jpg',
  lock: '/images/ss/lock.jpg',
  maintenance: '/images/ss/maintenance.jpg',
  reset: '/images/ss/reset.jpg',
  traffic: '/images/ss/trafic.jpg',
  street: '/images/ss/street.jpg',
};

export default screenshoots;
