const screenshoots = {
  dashboardv2: 'https://res.cloudinary.com/ux-maestro/image/upload/v1531879965/boss-lite/dashboardv2.jpg',
  trackingTable: 'https://res.cloudinary.com/ux-maestro/image/upload/v1531879978/boss-lite/tracking_table.jpg',
  crudTable: 'https://res.cloudinary.com/ux-maestro/image/upload/v1531879960/boss-lite/crud_table.jpg',
  treetable: 'https://res.cloudinary.com/ux-maestro/image/upload/v1531879979/boss-lite/treetable.jpg',
  datatable: 'https://res.cloudinary.com/ux-maestro/image/upload/v1531879965/boss-lite/datatable.jpg',
  ratting: 'https://res.cloudinary.com/ux-maestro/image/upload/v1531879972/boss-lite/ratting.jpg',
  slider: 'https://res.cloudinary.com/ux-maestro/image/upload/v1531879976/boss-lite/slider.jpg',
  texteditor: 'https://res.cloudinary.com/ux-maestro/image/upload/v1531879984/boss-lite/texteditor.jpg',
  upload: 'https://res.cloudinary.com/ux-maestro/image/upload/v1531879992/boss-lite/upload.jpg',
  imageLightbox: 'https://res.cloudinary.com/ux-maestro/image/upload/v1531879969/boss-lite/imageLightbox.jpg',
  dividers: 'https://res.cloudinary.com/ux-maestro/image/upload/v1531879962/boss-lite/dividers.jpg',
  pagination: 'https://res.cloudinary.com/ux-maestro/image/upload/v1531879972/boss-lite/pagination.jpg',
  sliderCarousel: 'https://res.cloudinary.com/ux-maestro/image/upload/v1531879974/boss-lite/sliderCarousel.jpg',
  sliderCarousel2: 'https://res.cloudinary.com/ux-maestro/image/upload/v1531879982/boss-lite/sliderCarousel2.jpg',
  chat: 'https://res.cloudinary.com/ux-maestro/image/upload/v1531879963/boss-lite/chat.jpg',
  email: 'https://res.cloudinary.com/ux-maestro/image/upload/v1531879966/boss-lite/email.jpg',
  ecommerce: 'https://res.cloudinary.com/ux-maestro/image/upload/v1531879963/boss-lite/ecommerce.jpg',
  socmed: 'https://res.cloudinary.com/ux-maestro/image/upload/v1531879984/boss-lite/socmed.jpg',
  profile: 'https://res.cloudinary.com/ux-maestro/image/upload/v1531879972/boss-lite/profile.jpg',
  gallery: 'https://res.cloudinary.com/ux-maestro/image/upload/v1531879978/boss-lite/gallery.jpg',
  lock: 'https://res.cloudinary.com/ux-maestro/image/upload/v1531879969/boss-lite/lock.jpg',
  maintenance: 'https://res.cloudinary.com/ux-maestro/image/upload/v1531879969/boss-lite/maintenance.jpg',
  reset: 'https://res.cloudinary.com/ux-maestro/image/upload/v1531879972/boss-lite/reset.jpg',
  traffic: 'https://res.cloudinary.com/ux-maestro/image/upload/v1531879990/boss-lite/trafic.jpg',
  street: 'https://res.cloudinary.com/ux-maestro/image/upload/v1531879989/boss-lite/street.jpg',
};

export default screenshoots;
